### ISSUE TITLE
Depreciated code - Request to work on it

### ISSUE THREAD

**Issue by rahulsain** [balaji-ramavathu/SmartAttendance#2]
Hi Sir, @luvk1412 @sheldontauro @Nitinrajsingh @balaji-ramavathu @rc4594 
I was thinking to make a similar app like this for my college, by following your prototype.
I see you made this Smart Attendance App in Java and is 2 years old now.
So, I kindly ask for your permission so that I can work on this app in Kotlin language and add more features with some improvisation of UI/UX.
We already have a attendance app, but there is some bug where student can’t see their attendance, but teacher mark our attendance successfully.
So, to fix this bug, I am also in touch with my faculties.

**Comment by Nitinrajsingh** [comment]
Hey sorry man for the late reply ya please go ahead and build it more than
happy . Just a small request is make sure people actually use it in
college.Otherwise all of it will be in vain

Atb Rahul sain

**Comment by rahulsain** [comment]
@Nitinrajsingh thanks for the approval. As this is huge project I will give my 100%

**Comment by Nitinrajsingh** [comment]
Np man normally professors give support to do the project for more than one
sem under them that might be useful if time isn’t sufficient
